# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24516563f5bc265aea9afa0ff67b8931367a06d4188cb7be150538e95c5223e7ba5bfc3dc975b40da2f40290073e8089f20de828ccac68ed3b4cd976d9e5d26d

test:
  secret_key_base: 5876c03b99ba05704a6e15fffdd06bc124a782cfd90c97f6390dfc770e68190934aa1e0435416a38401fa349d00749f2044ad50afb9792ed433cc99119908f1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
